additional_measurements = {
    "mesure_iem_003_value": "체지방율(%)",  
    "mesure_iem_004_value": "허리둘레(cm)",
    "mesure_iem_005_value": "이완기최저혈압(mmHg)",
    "mesure_iem_006_value": "수축기최고혈압(mmHg)",
    "mesure_iem_007_value": "악력_좌(kg)",
    "mesure_iem_008_value": "악력_우(kg)",
    "mesure_iem_009_value": "윗몸말아올리기(회)",
    "mesure_iem_010_value": "반복점프(회)",
    ##  
    "mesure_iem_012_value": "앉아윗몸앞으로굽히기(cm)",
    "mesure_iem_013_value": "일리노이(초)",
    "mesure_iem_014_value": "체공시간(초)",
    "mesure_iem_015_value": "협응력시간(초)",
    "mesure_iem_016_value": "협응력실수횟수(회)",
    "mesure_iem_017_value": "협응력계산결과값(초)",
    "mesure_iem_018_value": "BMI(kg/㎡)",
    "mesure_iem_019_value": "교차윗몸일으키기(회)",
    "mesure_iem_020_value": "왕복오래달리기(회)",
    "mesure_iem_021_value": "10M 4회 왕복달리기(초)",
    "mesure_iem_022_value": "제자리 멀리뛰기(cm)",
    "mesure_iem_023_value": "의자에앉았다일어서기(회)",
    "mesure_iem_024_value": "6분걷기(m)",
    "mesure_iem_025_value": "2분제자리걷기(회)",
    "mesure_iem_026_value": "의자에앉아 3M표적 돌아오기(초)",
    "mesure_iem_027_value": "8자보행(초)",
    "mesure_iem_028_value": "상대악력(%)",
    "mesure_iem_029_value": "피부두겹합",
    "mesure_iem_030_value": "왕복오래달리기출력(VO₂max)",
    "mesure_iem_031_value": "트레드밀_안정시(bpm)",
    "mesure_iem_032_value": "트레드밀_3분(bpm)",
    "mesure_iem_033_value": "트레드밀_6분(bpm)",
    "mesure_iem_034_value": "트레드밀_9분(bpm)",
    "mesure_iem_035_value": "트레드밀출력(VO₂max)",
    "mesure_iem_036_value": "스텝검사_회복시 심박수(bpm)",
    "mesure_iem_037_value": "스텝검사출력(VO₂max)",
    "mesure_iem_038_value": "허벅지_좌(cm)",
    "mesure_iem_039_value": "허벅지_우(cm)",
    "mesure_iem_040_value": "전신반응(초)",
    "mesure_iem_041_value": "성인체공시간(초)",
}